services:
  - type: web
    name: game-backend
    runtime: python
    pythonVersion: 3.13.0  # Line added for a compatible python version
    repo: https://github.com/MsalC1/Jacobs_Ladder  # Update with your repo URL
    rootDir: backend
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:$POST app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: game-db
          property: connectionString

databases:
  - name: game-db
    plan: free